spring:
  datasource:
    url: jdbc:mysql://containers-us-west-63.railway.app:7202/railway #?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&characterSetResults=utf8
    username: root
    password: SWmsdmbnOQ3RHDi0tn6u
